### PR TITLE
feature(DynamicLinks): add endpoint (WIP)

### PR DESCRIPTION
**Pull request by lucjac**

### CODE REVIEW

**Review by anta-semenov — APPROVED** [review]

**Comment by anta-semenov** [comment]
Actually, should we add those links to settings sync or give a get request type

**Comment by lucjac** [comment]
i'll rename the create one to 'sync' and it will also return one and create if needed

**Comment by anta-semenov** [comment]
> i'll rename the create one to 'sync' and it will also return one and create if needed

So this will create new one if there is no existing link already, right? if so then 👍

**Comment by lucjac** [comment]
yup exactly, and the refresh one is to explicitly create a new one

**Comment by anta-semenov** [comment]
I'm curious, to make a connection we will use different endpoint where we will send the link, is it correct?

**Comment by lucjac** [comment]
yeah i think it will be a different one but haven't put too much thought into this

**Pull request merged**
