### PR TITLE
feature(SyncConnections): add endpoint

### PR DESCRIPTION
**Pull request by lucjac**

### CODE REVIEW

**Review by anta-semenov — COMMENTED** [review]
Lucas do we need the request to establish endpoint? I believe we should be able to send a link and get back connection

**Comment by lucjac** [comment]
sorry i don't understand :D wdym?

**Comment by anta-semenov** [comment]
haha.
I mean. What will be the way to establish connection. When user opens invitation link we will have only link, this is the only thing we can send to backend, e.g. we won't know the id of the user who created the link (at list my assumption is that link is opaque)

**Comment by lucjac** [comment]
oh yes you're right, i get it! I'll introduce a request type as well. This is very much wip in general still

**Review by anta-semenov — APPROVED** [review]

**Pull request merged**
